UPDATE AM_APPLICATION_REGISTRATION 
SET INPUTS = REPLACE(INPUTS, CONCAT(CONCAT('sername":"', `username`), '"'), CONCAT(CONCAT('sername":"', `pseudonym`), '"')) 
WHERE (SELECT TENANT_ID FROM AM_SUBSCRIBER SUB WHERE SUB.SUBSCRIBER_ID = SUBSCRIBER_ID) = `tenant_id`
